service: serverless-go

provider:
  name: aws
  runtime: go1.x

#  stage: dev
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'lambda:InvokeFunction'
      Resource: arn:aws:lambda:${self:provider.region}:*:*

    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Scan
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_NAME}

  environment:
    DYNAMODB_TABLE_NAME: "Movies" #${self:service}-${opt:stage, self:provider.stage}-table

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  create:
    handler: bin/create
    events:
      - http:
          path: create
          method: post

  read:
    handler: bin/read
    events:
      - http:
          path: read
          method: get

  readAll:
    handler: bin/readAll
    events:
      - http:
          path: readAll
          method: get

resources:
  Resources:
    ReportDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: ExpirationTime
          Enabled: true